### ISSUE TITLE
Bubbles are not clearly and completely visible on hovering.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2482] opened 2017-03-03 13:09 UTC
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Map
•	Bubble chart

**PLATFORM:** 
•	 Windows10 / Edge14
•	Windows 7 + IE11

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Hover on bubbles.

**ACTUAL RESULTS:**
Bubbles aren’t clearly visible.

**EXPECTED RESULTS:**
Bubbles should be clearly visible.

**SCREENSHOT:**

![issue2 a](https://cloud.githubusercontent.com/assets/9950837/23552189/6fe78ee0-003c-11e7-8a18-1e07f60b6483.jpg)
![isuue2 b](https://cloud.githubusercontent.com/assets/9950837/23552188/6fe64bf2-003c-11e7-9711-31f7c9570a4f.jpg)

**Comment by angieskazka** [comment] 2017-03-09 08:58
can not reproduce on Windows10 / Edge14 or IE 11

**Comment by Legionivo** [comment] 2017-03-09 09:26
not reproduced on Win 7/ IE 11

**Comment by kuguarpwnz** [comment] 2017-03-31 06:57
can not reproduce on Windows10 / Edge14

**Comment by angieskazka** [comment] 2017-03-31 13:11
closing because can not reproduce

**Closed by angieskazka** 2017-03-31 13:11 UTC
Labels: type: bug
