### ISSUE TITLE
User is able to drag the canvas of chart even the zoom out pointer is selected 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2373] opened 2017-01-20 10:26 UTC
![1-20-2017 3-25-30 pm](https://cloud.githubusercontent.com/assets/9950837/22145855/bd637c1c-df24-11e6-9137-a89ff9ada1ff.jpg)

**Comment by angieskazka** [comment] 2017-03-10 08:16
duplicate of #2066 
fixed in #2452

**Closed by angieskazka** 2017-03-10 08:16 UTC
Labels: type: bug
