### ISSUE TITLE
The labels did not get enlarged when user clicks the present button

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2139] opened 2016-11-03 10:35 UTC
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart

**PLATFORM:** 
* Windows 7 / Google Chrome  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click on bubble  
3) Click on present button 

**ACTUAL RESULTS:**
The label did not gets enlarged 

**EXPECTED RESULTS:**
The label should enlarged when user clicks the present button

**Comment by angieskazka** [comment] 2016-11-08 10:48
duplicate of #1932

**Closed by angieskazka** 2016-11-08 10:48 UTC
Labels: type: duplicate
