### ISSUE TITLE
Countries are not translated if arabic language selected on Mountain chart 

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2462] opened 2017-02-27 15:20 UTC
**Steps to reproduce:**
1) go to http://tools-dev.gapminderdev.org/tools
2) select arabic language
3) go to `mountain chart` chart

**Actual result:**
List of languages to the left is not translated

**Expected result:**
All strings get translated

**Comment by angieskazka** [comment] 2017-03-03 10:51
this is a duplicate of #2445

**Closed by angieskazka** 2017-03-03 10:51 UTC
Labels: type: duplicate
