### ISSUE TITLE
The page behavior gets totally disturbed after some time when it remains idle

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1956] opened 2016-09-02 12:17 UTC
http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html#_width:1166&height:633&fullscreen:false&bodyC:null&resp-sect:true&info-sect:true&butt-sect:true&model_state_marker_axis/_y_zoomedMin:15.85&zoomedMax:85;&axis/_x_zoomedMin:300&zoomedMax:150000;&color_palette_oecd=#71c44c&others=#f05656&g77=#7487ef;&which=g77/_and/_oecd/_countries;&size_which=female/_long/_term/_unemployment/_rate/_percent;;;&language_id=se

**Comment by angieskazka** [comment] 2017-03-27 14:44
duplicate of #1921

**Closed by angieskazka** 2017-03-27 14:44 UTC
Labels: type: bug
