### ISSUE TITLE
Integers on label bar are overlapping

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1782] opened 2016-05-30 07:47 UTC
**SEVERITY:**  Minor

**MODULE:**  Bubble chart

**Platform:**
*   Windows 7 / Chrome 52.0
*    Windows 7 / Firefox 42.0

**RELEASE:** v0.13.11

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/
2)	Bubble Chart will be loaded.
3)	Click on Options icon
4)	Click on Label and select Time after clicking label dropdown
5)	Drag both sliders to the maximum
6)	Note that integers are overlapping 

**ACTUAL RESULTS:**
Integers on label bar are overlapping

**EXPECTED RESULTS:**
Overlapping should not be there

**SCREENSHOT:** 

![v0 13 11_ 05](https://cloud.githubusercontent.com/assets/9950837/15643057/9d8bba90-2664-11e6-9ca5-cfd20b3f4554.png)

**Comment by angieskazka** [comment] 2016-10-23 23:41
duplicate of The label values gets overlapped when user tries to increase the label size #1841

**Closed by angieskazka** 2016-10-23 23:41 UTC
