### ISSUE TITLE
Add size/color indicator value somewhere

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2128] opened 2016-10-30 22:45 UTC
A remark by a user on getsatisfaction which I think is a good idea:

https://getsatisfaction.com/gapminder/topics/population-count

A bit hard to understand but he's asking to see population numbers when hovering a bubble. Seems a very fair request. Same could be done for the color indicator, if set.
Either in the dialog in the sidebar, or in the label (when dialog is closed?)

**Comment by angieskazka** [comment] 2016-10-30 22:56
this is added in 0.16.1 and is currently a prod candidate
https://github.com/vizabi/vizabi/issues/1904#issuecomment-241462371 

exact values work both with sidebar expanded and collapsed
closing as duplicate of https://github.com/vizabi/vizabi/issues/1904

**Closed by angieskazka** 2016-10-30 22:56 UTC
