### ISSUE TITLE
After changing the indicators when user revert them to default manually The data gets changed but the year did not get back to its original position 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1898] opened 2016-08-08 12:30 UTC
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on x axis
3) Select health-> Mental health -> Sucide 
4) Observe the years 
5) Now click on x axis and select the default indicator 
6) Select income per person 

**ACTUAL RESULTS:**
The chart did not return to its default year values

**EXPECTED RESULTS:**
The chart year should return to its default values after switching the indicators 

**SCREENSHOT/GIF:**

http://g.recordit.co/3wLkndo32y.gif

**Comment by angieskazka** [comment] 2016-08-23 11:40
Duplicate of #1902

**Closed by angieskazka** 2016-08-23 11:40 UTC
Labels: type: bug
