### ISSUE TITLE
When user play the slider the mountain curves overflows the chart boundary  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2042] opened 2016-10-04 09:51 UTC
**SEVERITY:**  Major

**MODULE:**  Mountain Chart  

**PLATFORM:** 
- Windows 7 / Internet Explorer

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Click on mountain chart 
3) Click on show 
4) Click Albania check box 
5) Drag the slider to year 1990 

**ACTUAL RESULTS:** 
When user play the slider, the mountain peak overflows the chart boundary  

**EXPECTED RESULTS:**
When user play the slider, the mountain peak should be within the chart boundary  

**SCREENSHOT:**

![10-4-2016 2-40-23 pm](https://cloud.githubusercontent.com/assets/9950837/19069812/f914c398-8a41-11e6-95dc-49def91b3614.jpg)

**Comment by angieskazka** [comment] 2016-10-05 11:24
this is known, it's the result of incorrect assumption that mountains get higher towards the end of the time. needs refactoring, but it's not a bug. it's bad design.

**Comment by angieskazka** [comment] 2017-03-28 06:06
closing as duplicate of https://github.com/vizabi/vizabi/issues/1496

**Closed by angieskazka** 2017-03-28 06:06 UTC
Labels: type: bug
