### ISSUE TITLE
User is unable to change the bubbles color using color panel.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2530] opened 2017-03-15 07:26 UTC
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart

**PLATFORM:** 
•	 iPad Air 2 /Safari 9
•       iPad Air 2 / Google chrome

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Tap on "Options" button on right side.
3.Tap on color indicator and select Babies per women
4.Change the color and tap okay.

**ACTUAL RESULTS:**
Color doesn't change after selecting any color from color panel.

**EXPECTED RESULTS:**
Color should be changed.

**SCREEN SHOT:**
![unnamed](https://cloud.githubusercontent.com/assets/9950837/23937691/0a292cb6-0916-11e7-9303-fbd865032f67.png)

**Comment by kuguarpwnz** [comment] 2017-03-15 12:10
Can't reproduce. 

I found another issue: when you click on color and then OK, color panel is still visible. You need to double tap on color to close it.

**Comment by k6Labz** [comment] 2017-03-16 07:20
@kuguarpwnz  after selecting color from color wheel when i tap on any where on the  screen the color revert to default

**Comment by kuguarpwnz** [comment] 2017-03-27 10:32
Should be fixed on dev. Please retest

**Comment by k6Labz** [comment] 2017-03-27 11:19
Fixed on dev.

**Closed** 2017-03-27 12:53 UTC
Labels: type: bug
